name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: CheckOut
          uses: actions/checkout@v4
        - name: Welcome Message
          run: | 
            echo "My First Github Actions Job"
            ls -ltra
            cat README.md

        - name: Generate ASCII ArtWork
          run: cowsay -f dragon "Run for cover, I am a DRAGON....RAAWR" >> dragon.txt
 
        # - name: List Files
        #   run: ls

        # - name: Read File
        #   run: cat README.md